package com.realty.base.model;

// Generated 2014-4-13 11:32:40 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * BuildingUsage generated by hbm2java
 */
public class BuildingUsage implements java.io.Serializable {

	private int usageId;
	private String usageName;

	public BuildingUsage() {
	}

	public BuildingUsage(int usageId) {
		this.usageId = usageId;
	}

	public BuildingUsage(int usageId, String usageName) {
		this.usageId = usageId;
		this.usageName = usageName;
	}

	public int getUsageId() {
		return this.usageId;
	}

	public void setUsageId(int usageId) {
		this.usageId = usageId;
	}

	public String getUsageName() {
		return this.usageName;
	}

	public void setUsageName(String usageName) {
		this.usageName = usageName;
	}

}
