package com.realty.base.model;

// Generated 2014-4-13 11:32:40 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * BuildingStructure generated by hbm2java
 */
public class BuildingStructure implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int structureId;
	private String structureName;

	public BuildingStructure() {
	}

	public BuildingStructure(int structureId) {
		this.structureId = structureId;
	}

	public BuildingStructure(int structureId, String structureName) {
		this.structureId = structureId;
		this.structureName = structureName;
	}

	public int getStructureId() {
		return this.structureId;
	}

	public void setStructureId(int structureId) {
		this.structureId = structureId;
	}

	public String getStructureName() {
		return this.structureName;
	}

	public void setStructureName(String structureName) {
		this.structureName = structureName;
	}

}
