package com.realty.base.model;

// Generated 2014-4-13 11:32:40 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * BuildingForm generated by hbm2java
 */
public class BuildingForm implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String formId;
	private String formName;

	public BuildingForm() {
	}

	public BuildingForm(String formId) {
		this.formId = formId;
	}

	public BuildingForm(String formId, String formName) {
		this.formId = formId;
		this.formName = formName;
	}

	public String getFormId() {
		return this.formId;
	}

	public void setFormId(String formId) {
		this.formId = formId;
	}

	public String getFormName() {
		return this.formName;
	}

	public void setFormName(String formName) {
		this.formName = formName;
	}

}
