package com.realty.base.model;

// Generated 2014-4-28 13:33:40 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * BuildingPlanphoto generated by hbm2java
 */
public class BuildingPlanphoto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int planphotoId;
	private Integer buildingId;
	private String planPhoto;

	public BuildingPlanphoto() {
	}

	public BuildingPlanphoto(int planphotoId) {
		this.planphotoId = planphotoId;
	}

	public BuildingPlanphoto(int planphotoId, Integer buildingId,
			String planPhoto) {
		this.planphotoId = planphotoId;
		this.buildingId = buildingId;
		this.planPhoto = planPhoto;
	}

	public int getPlanphotoId() {
		return this.planphotoId;
	}

	public void setPlanphotoId(int planphotoId) {
		this.planphotoId = planphotoId;
	}

	public Integer getBuildingId() {
		return this.buildingId;
	}

	public void setBuildingId(Integer buildingId) {
		this.buildingId = buildingId;
	}

	public String getPlanPhoto() {
		return this.planPhoto;
	}

	public void setPlanPhoto(String planPhoto) {
		this.planPhoto = planPhoto;
	}

}
