package com.realty.base.model;

// Generated 2014-4-28 13:33:40 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * BuildingTypephoto generated by hbm2java
 */
public class BuildingTypephoto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int typephotoId;
	private Integer buildingId;
	private String typePhoto;

	public BuildingTypephoto() {
	}

	public BuildingTypephoto(int typephotoId) {
		this.typephotoId = typephotoId;
	}

	public BuildingTypephoto(int typephotoId, Integer buildingId,
			String typePhoto) {
		this.typephotoId = typephotoId;
		this.buildingId = buildingId;
		this.typePhoto = typePhoto;
	}

	public int getTypephotoId() {
		return this.typephotoId;
	}

	public void setTypephotoId(int typephotoId) {
		this.typephotoId = typephotoId;
	}

	public Integer getBuildingId() {
		return this.buildingId;
	}

	public void setBuildingId(Integer buildingId) {
		this.buildingId = buildingId;
	}

	public String getTypePhoto() {
		return this.typePhoto;
	}

	public void setTypePhoto(String typePhoto) {
		this.typePhoto = typePhoto;
	}

}
