package com.realty.base.model;

// Generated 2014-5-28 22:26:33 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * BuildingIntro generated by hbm2java
 */
public class BuildingIntro implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int buildintroId;
	private int buildingId;
	private String buildingName;
	private String address;
	private String buildingEast;
	private String buildingWest;
	private String buildingSouth;
	private String buildingNorth;
	private String landLevel;
	private String neighborhood;
	private String buildingInfor;
	private String nearRoad;
	private String publicTransport;
	private String commercialFacility;
	private String financingNstitution;
	private String school;
	private String hospital;
	private String other;
	private String internalFacility;
	private String electricityFacility;
	private String parkFacility;
	private String propertyManagement;
	private String environment;
	private Date collectTime;
	private String entryName;
	private Date entryTime;
	private String auditName;
	private Date auditTime;
	private Integer status;
	private String remarks;
	private Integer buildNum;
	private String floors;
	private Integer cells;
	private String networks;
	private Integer onehouses;

	public BuildingIntro() {
	}

	public BuildingIntro(int buildintroId, int buildingId,
			String buildingName) {
		this.buildintroId = buildintroId;
		this.buildingId = buildingId;
		this.buildingName = buildingName;
	}

	public BuildingIntro(int buildintroId, int buildingId,
			String buildingName, String address,
			String buildingEast, String buildingWest,
			String buildingSouth, String buildingNorth,
			String landLevel, String neighborhood,
			String buildingInfor, String nearRoad,
			String publicTransport, String commercialFacility,
			String financingNstitution, String school,
			String hospital, String other,
			String internalFacility, String electricityFacility,
			String parkFacility, String propertyManagement,
			String environment, Date collectTime, String entryName,
			Date entryTime, String auditName, Date auditTime,Integer status,
			String remarks, Integer buildNum, String floors,
			Integer cells, String networks, Integer onehouses) {
		this.buildintroId = buildintroId;
		this.buildingId = buildingId;
		this.buildingName = buildingName;
		this.address = address;
		this.buildingEast = buildingEast;
		this.buildingWest = buildingWest;
		this.buildingSouth = buildingSouth;
		this.buildingNorth = buildingNorth;
		this.landLevel = landLevel;
		this.neighborhood = neighborhood;
		this.buildingInfor = buildingInfor;
		this.nearRoad = nearRoad;
		this.publicTransport = publicTransport;
		this.commercialFacility = commercialFacility;
		this.financingNstitution = financingNstitution;
		this.school = school;
		this.hospital = hospital;
		this.other = other;
		this.internalFacility = internalFacility;
		this.electricityFacility = electricityFacility;
		this.parkFacility = parkFacility;
		this.propertyManagement = propertyManagement;
		this.environment = environment;
		this.collectTime = collectTime;
		this.entryName = entryName;
		this.entryTime = entryTime;
		this.auditName = auditName;
		this.auditTime = auditTime;
		this.status = status;
		this.remarks = remarks;
		this.buildNum = buildNum;
		this.floors = floors;
		this.cells = cells;
		this.networks = networks;
		this.onehouses = onehouses;
	}

	public int getBuildintroId() {
		return this.buildintroId;
	}

	public void setBuildintroId(int buildintroId) {
		this.buildintroId = buildintroId;
	}

	public int getBuildingId() {
		return this.buildingId;
	}

	public void setBuildingId(int buildingId) {
		this.buildingId = buildingId;
	}

	public String getBuildingName() {
		return this.buildingName;
	}

	public void setBuildingName(String buildingName) {
		this.buildingName = buildingName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getBuildingEast() {
		return this.buildingEast;
	}

	public void setBuildingEast(String buildingEast) {
		this.buildingEast = buildingEast;
	}

	public String getBuildingWest() {
		return this.buildingWest;
	}

	public void setBuildingWest(String buildingWest) {
		this.buildingWest = buildingWest;
	}

	public String getBuildingSouth() {
		return this.buildingSouth;
	}

	public void setBuildingSouth(String buildingSouth) {
		this.buildingSouth = buildingSouth;
	}

	public String getBuildingNorth() {
		return this.buildingNorth;
	}

	public void setBuildingNorth(String buildingNorth) {
		this.buildingNorth = buildingNorth;
	}

	public String getLandLevel() {
		return this.landLevel;
	}

	public void setLandLevel(String landLevel) {
		this.landLevel = landLevel;
	}

	public String getNeighborhood() {
		return this.neighborhood;
	}

	public void setNeighborhood(String neighborhood) {
		this.neighborhood = neighborhood;
	}

	public String getBuildingInfor() {
		return this.buildingInfor;
	}

	public void setBuildingInfor(String buildingInfor) {
		this.buildingInfor = buildingInfor;
	}

	public String getNearRoad() {
		return this.nearRoad;
	}

	public void setNearRoad(String nearRoad) {
		this.nearRoad = nearRoad;
	}

	public String getPublicTransport() {
		return this.publicTransport;
	}

	public void setPublicTransport(String publicTransport) {
		this.publicTransport = publicTransport;
	}

	public String getCommercialFacility() {
		return this.commercialFacility;
	}

	public void setCommercialFacility(String commercialFacility) {
		this.commercialFacility = commercialFacility;
	}

	public String getFinancingNstitution() {
		return this.financingNstitution;
	}

	public void setFinancingNstitution(String financingNstitution) {
		this.financingNstitution = financingNstitution;
	}

	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public String getHospital() {
		return this.hospital;
	}

	public void setHospital(String hospital) {
		this.hospital = hospital;
	}

	public String getOther() {
		return this.other;
	}

	public void setOther(String other) {
		this.other = other;
	}

	public String getInternalFacility() {
		return this.internalFacility;
	}

	public void setInternalFacility(String internalFacility) {
		this.internalFacility = internalFacility;
	}

	public String getElectricityFacility() {
		return this.electricityFacility;
	}

	public void setElectricityFacility(String electricityFacility) {
		this.electricityFacility = electricityFacility;
	}

	public String getParkFacility() {
		return this.parkFacility;
	}

	public void setParkFacility(String parkFacility) {
		this.parkFacility = parkFacility;
	}

	public String getPropertyManagement() {
		return this.propertyManagement;
	}

	public void setPropertyManagement(String propertyManagement) {
		this.propertyManagement = propertyManagement;
	}

	public String getEnvironment() {
		return this.environment;
	}

	public void setEnvironment(String environment) {
		this.environment = environment;
	}

	public Date getCollectTime() {
		return this.collectTime;
	}

	public void setCollectTime(Date collectTime) {
		this.collectTime = collectTime;
	}

	public String getEntryName() {
		return this.entryName;
	}

	public void setEntryName(String entryName) {
		this.entryName = entryName;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

	public String getAuditName() {
		return this.auditName;
	}

	public void setAuditName(String auditName) {
		this.auditName = auditName;
	}

	public Date getAuditTime() {
		return this.auditTime;
	}

	public void setAuditTime(Date auditTime) {
		this.auditTime = auditTime;   
	}
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Integer getBuildNum() {
		return this.buildNum;
	}

	public void setBuildNum(Integer buildNum) {
		this.buildNum = buildNum;
	}

	public String getFloors() {
		return this.floors;
	}

	public void setFloors(String floors) {
		this.floors = floors;
	}

	public Integer getCells() {
		return this.cells;
	}

	public void setCells(Integer cells) {
		this.cells = cells;
	}

	public String getNetworks() {
		return this.networks;
	}

	public void setNetworks(String networks) {
		this.networks = networks;
	}

	public Integer getOnehouses() {
		return this.onehouses;
	}

	public void setOnehouses(Integer onehouses) {
		this.onehouses = onehouses;
	}

}
