package com.realty.base.model;

// Generated 2014-4-28 13:33:40 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * BuildingLocationphoto generated by hbm2java
 */
public class BuildingLocationphoto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int locationphotoId;
	private Integer buildingId;
	private String locationPhoto;

	public BuildingLocationphoto() {
	}

	public BuildingLocationphoto(int locationphotoId) {
		this.locationphotoId = locationphotoId;
	}

	public BuildingLocationphoto(int locationphotoId, Integer buildingId,
			String locationPhoto) {
		this.locationphotoId = locationphotoId;
		this.buildingId = buildingId;
		this.locationPhoto = locationPhoto;
	}

	public int getLocationphotoId() {
		return this.locationphotoId;
	}

	public void setLocationphotoId(int locationphotoId) {
		this.locationphotoId = locationphotoId;
	}

	public Integer getBuildingId() {
		return this.buildingId;
	}

	public void setBuildingId(Integer buildingId) {
		this.buildingId = buildingId;
	}

	public String getLocationPhoto() {
		return this.locationPhoto;
	}

	public void setLocationPhoto(String locationPhoto) {
		this.locationPhoto = locationPhoto;
	}

}
