package com.realty.base.model;

// Generated 2014-5-29 12:10:33 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Culture generated by hbm2java
 */
public class Culture implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int cultureId;
	private String title;
	private Date data;
	private Integer culcategoryId;
	private String contents;
	private String culFile;
	private Set<CulturePhoto> culturePhotos = new HashSet<CulturePhoto>(0);

	public Culture() {
	}

	public Culture(int cultureId, String title) {
		this.cultureId = cultureId;
		this.title = title;
	}

	public Culture(int cultureId, String title, Date data,
			Integer culcategoryId, String contents, String culFile,
			Set<CulturePhoto> culturePhotos) {
		this.cultureId = cultureId;
		this.title = title;
		this.data = data;
		this.culcategoryId = culcategoryId;
		this.contents = contents;
		this.culFile = culFile;
		this.culturePhotos = culturePhotos;
	}

	public int getCultureId() {
		return this.cultureId;
	}

	public void setCultureId(int cultureId) {
		this.cultureId = cultureId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public Integer getCulcategoryId() {
		return this.culcategoryId;
	}

	public void setCulcategoryId(Integer culcategoryId) {
		this.culcategoryId = culcategoryId;
	}

	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	public String getCulFile() {
		return this.culFile;
	}

	public void setCulFile(String culFile) {
		this.culFile = culFile;
	}

	public Set<CulturePhoto> getCulturePhotos() {
		return this.culturePhotos;
	}

	public void setCulturePhotos(Set<CulturePhoto> culturePhotos) {
		this.culturePhotos = culturePhotos;
	}

}
