package com.realty.base.model;

// Generated 2014-5-29 12:10:33 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * CulturePhoto generated by hbm2java
 */
public class CulturePhoto implements java.io.Serializable {

	private int culphotoId;
	private Culture culture;
	private String culphoto;
	private String culdiscribe;

	public CulturePhoto() {
	}

	public CulturePhoto(int culphotoId) {
		this.culphotoId = culphotoId;
	}

	public CulturePhoto(int culphotoId, Culture culture, String culphoto,
			String culdiscribe) {
		this.culphotoId = culphotoId;
		this.culture = culture;
		this.culphoto = culphoto;
		this.culdiscribe = culdiscribe;
	}

	public int getCulphotoId() {
		return this.culphotoId;
	}

	public void setCulphotoId(int culphotoId) {
		this.culphotoId = culphotoId;
	}

	public Culture getCulture() {
		return this.culture;
	}

	public void setCulture(Culture culture) {
		this.culture = culture;
	}

	public String getCulphoto() {
		return this.culphoto;
	}

	public void setCulphoto(String culphoto) {
		this.culphoto = culphoto;
	}

	public String getCuldiscribe() {
		return this.culdiscribe;
	}

	public void setCuldiscribe(String culdiscribe) {
		this.culdiscribe = culdiscribe;
	}

}
