package com.realty.base.model;

// Generated 2014-5-19 15:17:50 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * Down generated by hbm2java
 */
public class Down implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int downId;
	private String title;
	private Integer downcategoryId;
	private Date date;
	private Integer downs;
	private String contents;
	private String downFile;

	public Down() {
	}

	public Down(int downId) {
		this.downId = downId;
	}

	public Down(int downId, String title, Integer downcategoryId,
			Date date, Integer downs, String contents, String downFile) {
		this.downId = downId;
		this.title = title;
		this.downcategoryId = downcategoryId;
		this.date = date;
		this.downs = downs;
		this.contents = contents;
		this.downFile = downFile;
	}

	public int getDownId() {
		return this.downId;
	}

	public void setDownId(int downId) {
		this.downId = downId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getDowncategoryId() {
		return this.downcategoryId;
	}

	public void setDowncategoryId(Integer downcategoryId) {
		this.downcategoryId = downcategoryId;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getDowns() {
		return this.downs;
	}

	public void setDowns(Integer downs) {
		this.downs = downs;
	}

	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	public String getDownFile() {
		return this.downFile;
	}

	public void setDownFile(String downFile) {
		this.downFile = downFile;
	}

}
