package com.realty.base.model;

// Generated 2014-5-28 22:26:33 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * Floor generated by hbm2java
 */
public class Floor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int floorId;
	private int buildingId;
	private Integer buildNum;
	private Integer unitNum;
	private Integer houseNum;
	private Double houseArea;
	private String present;
	private Integer decorateId;
	private Integer floorTotle;
	private Integer floorSaid;
	private Integer floorActual;
	private Integer usageId;
	private String houseType;
	private String orientation;
	private Double exchangePrice;
	private Double exchangeTotle;
	private Date exchangeTime;
	private String remarks;

	public Floor() {
	}

	public Floor(int floorId, int buildingId) {
		this.floorId = floorId;
		this.buildingId = buildingId;
	}

	public Floor(int floorId, int buildingId, Integer buildNum,
			Integer unitNum, Integer houseNum, Double houseArea,
			String present, Integer decorateId, Integer floorTotle,
			Integer floorSaid, Integer floorActual, Integer usageId,
			String houseType, String orientation,
			Double exchangePrice, Double exchangeTotle, Date exchangeTime,
			String remarks) {
		this.floorId = floorId;
		this.buildingId = buildingId;
		this.buildNum = buildNum;
		this.unitNum = unitNum;
		this.houseNum = houseNum;
		this.houseArea = houseArea;
		this.present = present;
		this.decorateId = decorateId;
		this.floorTotle = floorTotle;
		this.floorSaid = floorSaid;
		this.floorActual = floorActual;
		this.usageId = usageId;
		this.houseType = houseType;
		this.orientation = orientation;
		this.exchangePrice = exchangePrice;
		this.exchangeTotle = exchangeTotle;
		this.exchangeTime = exchangeTime;
		this.remarks = remarks;
	}

	public int getFloorId() {
		return this.floorId;
	}

	public void setFloorId(int floorId) {
		this.floorId = floorId;
	}

	public int getBuildingId() {
		return this.buildingId;
	}

	public void setBuildingId(int buildingId) {
		this.buildingId = buildingId;
	}

	public Integer getBuildNum() {
		return this.buildNum;
	}

	public void setBuildNum(Integer buildNum) {
		this.buildNum = buildNum;
	}

	public Integer getUnitNum() {
		return this.unitNum;
	}

	public void setUnitNum(Integer unitNum) {
		this.unitNum = unitNum;
	}

	public Integer getHouseNum() {
		return this.houseNum;
	}

	public void setHouseNum(Integer houseNum) {
		this.houseNum = houseNum;
	}

	public Double getHouseArea() {
		return this.houseArea;
	}

	public void setHouseArea(Double houseArea) {
		this.houseArea = houseArea;
	}

	public String getPresent() {
		return this.present;
	}

	public void setPresent(String present) {
		this.present = present;
	}

	public Integer getDecorateId() {
		return this.decorateId;
	}

	public void setDecorateId(Integer decorateId) {
		this.decorateId = decorateId;
	}

	public Integer getFloorTotle() {
		return this.floorTotle;
	}

	public void setFloorTotle(Integer floorTotle) {
		this.floorTotle = floorTotle;
	}

	public Integer getFloorSaid() {
		return this.floorSaid;
	}

	public void setFloorSaid(Integer floorSaid) {
		this.floorSaid = floorSaid;
	}

	public Integer getFloorActual() {
		return this.floorActual;
	}

	public void setFloorActual(Integer floorActual) {
		this.floorActual = floorActual;
	}

	public Integer getUsageId() {
		return this.usageId;
	}

	public void setUsageId(Integer usageId) {
		this.usageId = usageId;
	}

	public String getHouseType() {
		return this.houseType;
	}

	public void setHouseType(String houseType) {
		this.houseType = houseType;
	}

	public String getOrientation() {
		return this.orientation;
	}

	public void setOrientation(String orientation) {
		this.orientation = orientation;
	}

	public Double getExchangePrice() {
		return this.exchangePrice;
	}

	public void setExchangePrice(Double exchangePrice) {
		this.exchangePrice = exchangePrice;
	}

	public Double getExchangeTotle() {
		return this.exchangeTotle;
	}

	public void setExchangeTotle(Double exchangeTotle) {
		this.exchangeTotle = exchangeTotle;
	}

	public Date getExchangeTime() {
		return this.exchangeTime;
	}

	public void setExchangeTime(Date exchangeTime) {
		this.exchangeTime = exchangeTime;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
