package com.realty.base.model;

// Generated 2014-5-27 11:24:08 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * FloorUsage generated by hbm2java
 */
public class FloorUsage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int usageId;
	private String usageName;

	public FloorUsage() {
	}

	public FloorUsage(int usageId) {
		this.usageId = usageId;
	}

	public FloorUsage(int usageId, String usageName) {
		this.usageId = usageId;
		this.usageName = usageName;
	}

	public int getUsageId() {
		return this.usageId;
	}

	public void setUsageId(int usageId) {
		this.usageId = usageId;
	}

	public String getUsageName() {
		return this.usageName;
	}

	public void setUsageName(String usageName) {
		this.usageName = usageName;
	}

}
