package com.realty.base.model;

// Generated 2014-7-20 10:18:14 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * LandPoss generated by hbm2java
 */
public class LandPoss implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5694195330975989241L;
	private int landpossId;
	private String landpossName;
	//private Set<Land> lands = new HashSet<Land>(0);

	public LandPoss() {
	}

	public LandPoss(int landpossId) {
		this.landpossId = landpossId;
	}

/*	public LandPoss(int landpossId, String landpossName, Set<Land> lands) {
		this.landpossId = landpossId;
		this.landpossName = landpossName;
		this.lands = lands;
	}*/
	public LandPoss(int landpossId, String landpossName) {
		this.landpossId = landpossId;
		this.landpossName = landpossName;
		}
	
	public int getLandpossId() {
		return this.landpossId;
	}

	public void setLandpossId(int landpossId) {
		this.landpossId = landpossId;
	}

	public String getLandpossName() {
		return this.landpossName;
	}

	public void setLandpossName(String landpossName) {
		this.landpossName = landpossName;
	}

	/*public Set<Land> getLands() {
		return this.lands;
	}

	public void setLands(Set<Land> lands) {
		this.lands = lands;
	}*/

}
