package com.realty.base.model;

// Generated 2014-7-20 10:18:14 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * LandLocation generated by hbm2java
 */
public class LandLocation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1177668572044641199L;
	private int landlocationId;
	private int landId;
	private String photopath;
	private String description;

	public LandLocation() {
	}

	public LandLocation(int landlocationId, int landId) {
		this.landlocationId = landlocationId;
		this.landId = landId;
	}

	public LandLocation(int landlocationId, int landId,
			String photopath) {
		this.landlocationId = landlocationId;
		this.landId = landId;
		this.photopath = photopath;
	}

	public int getLandlocationId() {
		return this.landlocationId;
	}

	public void setLandlocationId(int landlocationId) {
		this.landlocationId = landlocationId;
	}

	public int getLandId() {
		return this.landId;
	}

	public void setLandId(int landId) {
		this.landId = landId;
	}

	public String getPhotopath() {
		return this.photopath;
	}

	public void setPhotopath(String photopath) {
		this.photopath = photopath;
	}

	

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
