package com.realty.base.model;

// Generated 2014-7-20 10:18:14 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * LandPhoto generated by hbm2java
 */
public class LandPhoto implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 715595064203829486L;
	private int landphotoId;
	private int landId;
	private String photopath;
	private String description;

	public LandPhoto() {
	}

	public LandPhoto(int landphotoId, int landId) {
		this.landphotoId = landphotoId;
		this.landId = landId;
	}

	public LandPhoto(int landphotoId, int landId, String photopath) {
		this.landphotoId = landphotoId;
		this.landId = landId;
		this.photopath = photopath;
	}

	public int getLandphotoId() {
		return this.landphotoId;
	}

	public void setLandphotoId(int landphotoId) {
		this.landphotoId = landphotoId;
	}

	public int getLandId() {
		return this.landId;
	}

	public void setLandId(int landId) {
		this.landId = landId;
	}

	public String getPhotopath() {
		return this.photopath;
	}

	public void setPhotopath(String photopath) {
		this.photopath = photopath;
	}



	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
