package com.realty.base.model;

// Generated 2014-7-24 15:56:47 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * LandAllot generated by hbm2java
 */
public class LandAllot implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2044737170586795263L;
	private int landallotId;
	private Integer landId;
	private Integer landusageId;
	private String landusageDetail;
	private Double landArea;
	private Double planArea;
	private Integer housenum;
	private String remarks;

	public LandAllot() {
	}

	public LandAllot(int landallotId) {
		this.landallotId = landallotId;
	}

	public LandAllot(int landallotId, Integer landId, Integer landusageId,
			String landusageDetail, Double landArea, Double planArea,
			Integer housenum, String remarks) {
		this.landallotId = landallotId;
		this.landId = landId;
		this.landusageId = landusageId;
		this.landusageDetail = landusageDetail;
		this.landArea = landArea;
		this.planArea = planArea;
		this.housenum = housenum;
		this.remarks = remarks;
	}

	public int getLandallotId() {
		return this.landallotId;
	}

	public void setLandallotId(int landallotId) {
		this.landallotId = landallotId;
	}

	public Integer getLandId() {
		return this.landId;
	}

	public void setLandId(Integer landId) {
		this.landId = landId;
	}

	public Integer getLandusageId() {
		return this.landusageId;
	}

	public void setLandusageId(Integer landusageId) {
		this.landusageId = landusageId;
	}

	public String getLandusageDetail() {
		return this.landusageDetail;
	}

	public void setLandusageDetail(String landusageDetail) {
		this.landusageDetail = landusageDetail;
	}

	public Double getLandArea() {
		return this.landArea;
	}

	public void setLandArea(Double landArea) {
		this.landArea = landArea;
	}

	public Double getPlanArea() {
		return this.planArea;
	}

	public void setPlanArea(Double planArea) {
		this.planArea = planArea;
	}

	public Integer getHousenum() {
		return this.housenum;
	}

	public void setHousenum(Integer housenum) {
		this.housenum = housenum;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
