package com.realty.base.model;

// Generated 2014-7-20 10:18:14 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * LandSellway generated by hbm2java
 */
public class LandSellway implements java.io.Serializable {

	private int sellwayId;
	private String sellwayName;
	
	public LandSellway() {
	}

	public LandSellway(int sellwayId) {
		this.sellwayId = sellwayId;
	}

	public LandSellway(int sellwayId, String sellwayName) {
		this.sellwayId = sellwayId;
		this.sellwayName = sellwayName;
	}

	public int getSellwayId() {
		return this.sellwayId;
	}

	public void setSellwayId(int sellwayId) {
		this.sellwayId = sellwayId;
	}

	public String getSellwayName() {
		return this.sellwayName;
	}

	public void setSellwayName(String sellwayName) {
		this.sellwayName = sellwayName;
	}


}
