package com.realty.base.model;

// Generated 2014-7-20 10:18:14 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * LandUsage generated by hbm2java
 */
public class LandUsage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 59486769622149222L;
	private int usageId;
	private String usageName;

	public LandUsage() {
	}

	public LandUsage(int usageId) {
		this.usageId = usageId;
	}

	public LandUsage(int usageId, String usageName) {
		this.usageId = usageId;
		this.usageName = usageName;
	}

	public int getUsageId() {
		return this.usageId;
	}

	public void setUsageId(int usageId) {
		this.usageId = usageId;
	}

	public String getUsageName() {
		return this.usageName;
	}

	public void setUsageName(String usageName) {
		this.usageName = usageName;
	}

	
}
