package com.realty.base.model;

// Generated 2014-7-20 10:18:14 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Land generated by hbm2java
 */
public class Land implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 775542537650092852L;
	private int landId;
	private LandPoss landPoss;
	private LandSellway landSellway;
	private LandUsage landUsage;
	private String landName;
	private Date auctionTime;
	private Integer regionId;
	private String address;
	private String landLevel;
	private String landExploit;
	private String heightLimit;
	private Double landArea;
	private String plotRatio;
	private String buildingDensity;
	private String greeningRatio;
	private Integer sellYear;
	private Double planArea;
	private Integer initialPrice;
	private Integer builddealPrice;
	private Double landdealPrice;
	private Double dealTotle;
	private String premiumRate;
	private String buyer;
	private Date dealDate;
	private String sellAnnounce;
	private String dealAnnounce;
	private String landmap;
	private String landIntr;
	private String projectIntro;
	private Double longitude;
	private Double latitude;
	private Integer entryId;
	private String entryName;
	private Date enrtyTime;
	private String auditName;
	private Date auditTime;
	private Integer status;
	private String remarks;
	private Integer landOwnid;
	private Integer allotFlag;
	private Date announceTime;
	private Date zpgTime;
	private Date auctionEndtime;
	private String landNumber;
	private Double landAllarea;
	private Double planAllarea;
	private String getway;
	private String sellAnnonumber;
	private String dealAnnonumber;
	private Set<LandPhoto> landPhotos = new HashSet<LandPhoto>(0); //下面的，默认.xml是延迟加载
	private Set<LandLocation> landLocations = new HashSet<LandLocation>(0);
	private Set<LandAllot> landAllots = new HashSet<LandAllot>(0);
	private Set<LandMutiusage> landMutiusages = new HashSet<LandMutiusage>(0);

	public Land() {
	}

	public Land(int landId) {
		this.landId = landId;
	}

	public Land(int landId, LandPoss landPoss, LandSellway landSellway,
			LandUsage landUsage, String landName, Date auctionTime,
			Integer regionId, String address, String landLevel,
			String landExploit, String heightLimit,
			Double landArea, String plotRatio,
			String buildingDensity, String greeningRatio,
			Integer sellYear, Double planArea, int initialPrice,
			int builddealPrice, Double landdealPrice, Double dealTotle,
			String premiumRate, String buyer, Date dealDate,
			String sellAnnounce, String dealAnnounce,
			String landmap, String landIntr, String projectIntro,
			Double longitude, Double latitude, Integer entryId,
			String entryName, Date enrtyTime, String auditName,
			Date auditTime, Integer status, String remarks,
			Integer landOwnid, Integer allotFlag, Date announceTime,
			Date zpgTime, Date auctionEndtime, String landNumber,
			Double landAllarea, Double planAllarea, String getway,
			String sellAnnonumber, String dealAnnonumber,
			Set<LandPhoto> landPhotos, Set<LandLocation> landLocations,
			Set<LandAllot> landAllots, Set<LandMutiusage> landMutiusages) {
		this.landId = landId;
		this.landPoss = landPoss;
		this.landSellway = landSellway;
		this.landUsage = landUsage;
		this.landName = landName;
		this.auctionTime = auctionTime;
		this.regionId = regionId;
		this.address = address;
		this.landLevel = landLevel;
		this.landExploit = landExploit;
		this.heightLimit = heightLimit;
		this.landArea = landArea;
		this.plotRatio = plotRatio;
		this.buildingDensity = buildingDensity;
		this.greeningRatio = greeningRatio;
		this.sellYear = sellYear;
		this.planArea = planArea;
		this.initialPrice = initialPrice;
		this.builddealPrice = builddealPrice;
		this.landdealPrice = landdealPrice;
		this.dealTotle = dealTotle;
		this.premiumRate = premiumRate;
		this.buyer = buyer;
		this.dealDate = dealDate;
		this.sellAnnounce = sellAnnounce;
		this.dealAnnounce = dealAnnounce;
		this.landmap = landmap;
		this.landIntr = landIntr;
		this.projectIntro = projectIntro;
		this.longitude = longitude;
		this.latitude = latitude;
		this.entryId = entryId;
		this.entryName = entryName;
		this.enrtyTime = enrtyTime;
		this.auditName = auditName;
		this.auditTime = auditTime;
		this.status = status;
		this.remarks = remarks;
		this.landOwnid = landOwnid;
		this.allotFlag = allotFlag;
		this.announceTime = announceTime;
		this.zpgTime = zpgTime;
		this.auctionEndtime = auctionEndtime;
		this.landNumber = landNumber;
		this.landAllarea = landAllarea;
		this.planAllarea = planAllarea;
		this.getway = getway;
		this.sellAnnonumber = sellAnnonumber;
		this.dealAnnonumber = dealAnnonumber;
		this.landPhotos = landPhotos;
		this.landLocations = landLocations;
		this.landAllots = landAllots;
		this.landMutiusages = landMutiusages;
	}

	public int getLandId() {
		return this.landId;
	}

	public void setLandId(int landId) {
		this.landId = landId;
	}

	public LandPoss getLandPoss() {
		return this.landPoss;
	}

	public void setLandPoss(LandPoss landPoss) {
		this.landPoss = landPoss;
	}

	public LandSellway getLandSellway() {
		return this.landSellway;
	}

	public void setLandSellway(LandSellway landSellway) {
		this.landSellway = landSellway;
	}

	public LandUsage getLandUsage() {
		return this.landUsage;
	}

	public void setLandUsage(LandUsage landUsage) {
		this.landUsage = landUsage;
	}

	public String getLandName() {
		return this.landName;
	}

	public void setLandName(String landName) {
		this.landName = landName;
	}

	public Date getAuctionTime() {
		return this.auctionTime;
	}

	public void setAuctionTime(Date auctionTime) {
		this.auctionTime = auctionTime;
	}

	public Integer getRegionId() {
		return this.regionId;
	}

	public void setRegionId(Integer regionId) {
		this.regionId = regionId;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getLandLevel() {
		return this.landLevel;
	}

	public void setLandLevel(String landLevel) {
		this.landLevel = landLevel;
	}

	public String getLandExploit() {
		return this.landExploit;
	}

	public void setLandExploit(String landExploit) {
		this.landExploit = landExploit;
	}

	public String getHeightLimit() {
		return this.heightLimit;
	}

	public void setHeightLimit(String heightLimit) {
		this.heightLimit = heightLimit;
	}

	public Double getLandArea() {
		return this.landArea;
	}

	public void setLandArea(Double landArea) {
		this.landArea = landArea;
	}

	public String getPlotRatio() {
		return this.plotRatio;
	}

	public void setPlotRatio(String plotRatio) {
		this.plotRatio = plotRatio;
	}

	public String getBuildingDensity() {
		return this.buildingDensity;
	}

	public void setBuildingDensity(String buildingDensity) {
		this.buildingDensity = buildingDensity;
	}

	public String getGreeningRatio() {
		return this.greeningRatio;
	}

	public void setGreeningRatio(String greeningRatio) {
		this.greeningRatio = greeningRatio;
	}

	public Integer getSellYear() {
		return this.sellYear;
	}

	public void setSellYear(Integer sellYear) {
		this.sellYear = sellYear;
	}

	public Double getPlanArea() {
		return this.planArea;
	}

	public void setPlanArea(Double planArea) {
		this.planArea = planArea;
	}

	public Integer getInitialPrice() {
		return this.initialPrice;
	}

	public void setInitialPrice(Integer initialPrice) {
		this.initialPrice = initialPrice;
	}

	public Integer getBuilddealPrice() {
		return this.builddealPrice;
	}

	public void setBuilddealPrice(Integer builddealPrice) {
		this.builddealPrice = builddealPrice;
	}

	public Double getLanddealPrice() {
		return this.landdealPrice;
	}

	public void setLanddealPrice(Double landdealPrice) {
		this.landdealPrice = landdealPrice;
	}

	public Double getDealTotle() {
		return this.dealTotle;
	}

	public void setDealTotle(Double dealTotle) {
		this.dealTotle = dealTotle;
	}

	public String getPremiumRate() {
		return this.premiumRate;
	}

	public void setPremiumRate(String premiumRate) {
		this.premiumRate = premiumRate;
	}

	public String getBuyer() {
		return this.buyer;
	}

	public void setBuyer(String buyer) {
		this.buyer = buyer;
	}

	public Date getDealDate() {
		return this.dealDate;
	}

	public void setDealDate(Date dealDate) {
		this.dealDate = dealDate;
	}

	public String getSellAnnounce() {
		return this.sellAnnounce;
	}

	public void setSellAnnounce(String sellAnnounce) {
		this.sellAnnounce = sellAnnounce;
	}

	public String getDealAnnounce() {
		return this.dealAnnounce;
	}

	public void setDealAnnounce(String dealAnnounce) {
		this.dealAnnounce = dealAnnounce;
	}

	public String getLandmap() {
		return this.landmap;
	}

	public void setLandmap(String landmap) {
		this.landmap = landmap;
	}

	public String getLandIntr() {
		return this.landIntr;
	}

	public void setLandIntr(String landIntr) {
		this.landIntr = landIntr;
	}

	public String getProjectIntro() {
		return this.projectIntro;
	}

	public void setProjectIntro(String projectIntro) {
		this.projectIntro = projectIntro;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Integer getEntryId() {
		return this.entryId;
	}

	public void setEntryId(Integer entryId) {
		this.entryId = entryId;
	}

	public String getEntryName() {
		return this.entryName;
	}

	public void setEntryName(String entryName) {
		this.entryName = entryName;
	}

	public Date getEnrtyTime() {
		return this.enrtyTime;
	}

	public void setEnrtyTime(Date enrtyTime) {
		this.enrtyTime = enrtyTime;
	}

	public String getAuditName() {
		return this.auditName;
	}

	public void setAuditName(String auditName) {
		this.auditName = auditName;
	}

	public Date getAuditTime() {
		return this.auditTime;
	}

	public void setAuditTime(Date auditTime) {
		this.auditTime = auditTime;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Integer getLandOwnid() {
		return this.landOwnid;
	}

	public void setLandOwnid(Integer landOwnid) {
		this.landOwnid = landOwnid;
	}

	public Integer getAllotFlag() {
		return this.allotFlag;
	}

	public void setAllotFlag(Integer allotFlag) {
		this.allotFlag = allotFlag;
	}

	public Date getAnnounceTime() {
		return this.announceTime;
	}

	public void setAnnounceTime(Date announceTime) {
		this.announceTime = announceTime;
	}

	public Date getZpgTime() {
		return this.zpgTime;
	}

	public void setZpgTime(Date zpgTime) {
		this.zpgTime = zpgTime;
	}

	public Date getAuctionEndtime() {
		return this.auctionEndtime;
	}

	public void setAuctionEndtime(Date auctionEndtime) {
		this.auctionEndtime = auctionEndtime;
	}

	public String getLandNumber() {
		return this.landNumber;
	}

	public void setLandNumber(String landNumber) {
		this.landNumber = landNumber;
	}

	public Double getLandAllarea() {
		return this.landAllarea;
	}

	public void setLandAllarea(Double landAllarea) {
		this.landAllarea = landAllarea;
	}

	public Double getPlanAllarea() {
		return this.planAllarea;
	}

	public void setPlanAllarea(Double planAllarea) {
		this.planAllarea = planAllarea;
	}

	public String getGetway() {
		return this.getway;
	}

	public void setGetway(String getway) {
		this.getway = getway;
	}

	public String getSellAnnonumber() {
		return this.sellAnnonumber;
	}

	public void setSellAnnonumber(String sellAnnonumber) {
		this.sellAnnonumber = sellAnnonumber;
	}

	public String getDealAnnonumber() {
		return this.dealAnnonumber;
	}

	public void setDealAnnonumber(String dealAnnonumber) {
		this.dealAnnonumber = dealAnnonumber;
	}

	public Set<LandPhoto> getLandPhotos() {
		return this.landPhotos;
	}

	public void setLandPhotos(Set<LandPhoto> landPhotos) {
		this.landPhotos = landPhotos;
	}

	public Set<LandLocation> getLandLocations() {
		return this.landLocations;
	}

	public void setLandLocations(Set<LandLocation> landLocations) {
		this.landLocations = landLocations;
	}

	public Set<LandAllot> getLandAllots() {
		return this.landAllots;
	}

	public void setLandAllots(Set<LandAllot> landAllots) {
		this.landAllots = landAllots;
	}

	public Set<LandMutiusage> getLandMutiusages() {
		return this.landMutiusages;
	}

	public void setLandMutiusages(Set<LandMutiusage> landMutiusages) {
		this.landMutiusages = landMutiusages;
	}

}
