package com.realty.base.model;

// Generated 2014-5-29 10:34:40 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * Law generated by hbm2java
 */
public class Law implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int lawId;
	private String name;
	private Integer number;
	private String company;
	private Date date;
	private String keyword;
	private String summary;
	private String contents;
	private Integer lawcategoryId;
	private String lawFile;

	public Law() {
	}

	public Law(int lawId, String name) {
		this.lawId = lawId;
		this.name = name;
	}

	public Law(int lawId, String name, Integer number,
			String company, Date date, String keyword,
			String summary, String contents, Integer lawcategoryId,
			String lawFile) {
		this.lawId = lawId;
		this.name = name;
		this.number = number;
		this.company = company;
		this.date = date;
		this.keyword = keyword;
		this.summary = summary;
		this.contents = contents;
		this.lawcategoryId = lawcategoryId;
		this.lawFile = lawFile;
	}

	public int getLawId() {
		return this.lawId;
	}

	public void setLawId(int lawId) {
		this.lawId = lawId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	public Integer getLawcategoryId() {
		return this.lawcategoryId;
	}

	public void setLawcategoryId(Integer lawcategoryId) {
		this.lawcategoryId = lawcategoryId;
	}

	public String getLawFile() {
		return this.lawFile;
	}

	public void setLawFile(String lawFile) {
		this.lawFile = lawFile;
	}

}
