package com.realty.base.model;

// Generated 2014-5-13 9:30:50 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * Level generated by hbm2java
 */
public class Level implements java.io.Serializable {

	private int memroleId;
	private Serializable rolename;

	public Level() {
	}

	public Level(int memroleId, Serializable rolename) {
		this.memroleId = memroleId;
		this.rolename = rolename;
	}

	public int getMemroleId() {
		return this.memroleId;
	}

	public void setMemroleId(int memroleId) {
		this.memroleId = memroleId;
	}

	public Serializable getRolename() {
		return this.rolename;
	}

	public void setRolename(Serializable rolename) {
		this.rolename = rolename;
	}

}
