package com.realty.base.model;

// Generated 2014-5-29 12:10:33 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * Macro generated by hbm2java
 */
public class Macro implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int macroId;
	private String name;
	private Integer number;
	private Date date;
	private String keyword;
	private String summary;
	private String contents;
	private Integer macrocategoryId;
	private String macrocategoryFile;

	public Macro() {
	}

	public Macro(int macroId, String name) {
		this.macroId = macroId;
		this.name = name;
	}

	public Macro(int macroId, String name, Integer number, Date date,
			String keyword, String summary, String contents,
			Integer macrocategoryId, String macrocategoryFile) {
		this.macroId = macroId;
		this.name = name;
		this.number = number;
		this.date = date;
		this.keyword = keyword;
		this.summary = summary;
		this.contents = contents;
		this.macrocategoryId = macrocategoryId;
		this.macrocategoryFile = macrocategoryFile;
	}

	public int getMacroId() {
		return this.macroId;
	}

	public void setMacroId(int macroId) {
		this.macroId = macroId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	public Integer getMacrocategoryId() {
		return this.macrocategoryId;
	}

	public void setMacrocategoryId(Integer macrocategoryId) {
		this.macrocategoryId = macrocategoryId;
	}

	public String getMacrocategoryFile() {
		return this.macrocategoryFile;
	}

	public void setMacrocategoryFile(String macrocategoryFile) {
		this.macrocategoryFile = macrocategoryFile;
	}

}
