package com.realty.base.model;

// Generated 2014-3-27 17:27:36 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * Manager generated by hbm2java
 */
public class Manager implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int manId;
	private String name;
	private String password;
	private String manrole;

	public Manager() {
	}

	public Manager(int manId, String name, String password) {
		this.manId = manId;
		this.name = name;
		this.password = password;
	}

	public Manager(int manId, String name, String password,
			String manrole) {
		this.manId = manId;
		this.name = name;
		this.password = password;
		this.manrole = manrole;
	}

	public int getManId() {
		return this.manId;
	}

	public void setManId(int manId) {
		this.manId = manId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getManrole() {
		return this.manrole;
	}

	public void setManrole(String manrole) {
		this.manrole = manrole;
	}

}
