package com.realty.base.model;

// Generated 2014-4-10 15:07:28 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.sql.Date;

/**
 * Memeber generated by hbm2java
 */
public class Member implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int memberId;
	private String name;
	private String password;
	private String EMail;
	private String querstion;
	private String answer;
	private Date createTime;
	private Integer memrole;
	private String registerId;

	public Member() {
	}

	public Member(int memberId, String name, String password) {
		this.memberId = memberId;
		this.name = name;
		this.password = password;
	}

	public Member(int memberId, String name, String password,
			String EMail, String querstion, String answer,
			Date createTime, Integer memrole, String registerId) {
		this.memberId = memberId;
		this.name = name;
		this.password = password;
		this.EMail = EMail;
		this.querstion = querstion;
		this.answer = answer;
		this.createTime = createTime;
		this.memrole = memrole;
		this.registerId=registerId;
	}

	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	public String getQuerstion() {
		return this.querstion;
	}

	public void setQuerstion(String querstion) {
		this.querstion = querstion;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createtime2) {
		this.createTime = createtime2;
	}

	public Integer getMemrole() {
		return this.memrole;
	}

	public void setMemrole(Integer memrole) {
		this.memrole = memrole;
	}

	public String getRegisterId() {
		return registerId;
	}

	public void setRegisterId(String registerId) {
		this.registerId = registerId;
	}

	

}
