package com.realty.base.model;

// Generated 2014-5-29 12:10:33 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * Micro generated by hbm2java
 */
public class Micro implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int microId;
	private String name;
	private Integer number;
	private Date data;
	private String keyword;
	private String summary;
	private String contents;
	private Integer microcategoryId;
	private String microcategoryFile;

	public Micro() {
	}

	public Micro(int microId, String name) {
		this.microId = microId;
		this.name = name;
	}

	public Micro(int microId, String name, Integer number, Date data,
			String keyword, String summary, String contents,
			Integer microcategoryId, String microcategoryFile) {
		this.microId = microId;
		this.name = name;
		this.number = number;
		this.data = data;
		this.keyword = keyword;
		this.summary = summary;
		this.contents = contents;
		this.microcategoryId = microcategoryId;
		this.microcategoryFile = microcategoryFile;
	}

	public int getMicroId() {
		return this.microId;
	}

	public void setMicroId(int microId) {
		this.microId = microId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	public Integer getMicrocategoryId() {
		return this.microcategoryId;
	}

	public void setMicrocategoryId(Integer microcategoryId) {
		this.microcategoryId = microcategoryId;
	}

	public String getMicrocategoryFile() {
		return this.microcategoryFile;
	}

	public void setMicrocategoryFile(String microcategoryFile) {
		this.microcategoryFile = microcategoryFile;
	}

}
