package com.realty.base.model;

// Generated 2014-5-27 21:22:47 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * PriceType generated by hbm2java
 */
public class PriceType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int pricetypeId;
	private String pricetypeName;

	public PriceType() {
	}

	public PriceType(int pricetypeId) {
		this.pricetypeId = pricetypeId;
	}

	public PriceType(int pricetypeId, String pricetypeName) {
		this.pricetypeId = pricetypeId;
		this.pricetypeName = pricetypeName;
	}

	public int getPricetypeId() {
		return this.pricetypeId;
	}

	public void setPricetypeId(int pricetypeId) {
		this.pricetypeId = pricetypeId;
	}

	public String getPricetypeName() {
		return this.pricetypeName;
	}

	public void setPricetypeName(String pricetypeName) {
		this.pricetypeName = pricetypeName;
	}

}
