package com.realty.base.model;

// Generated 2014-5-5 15:28:23 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int projectId;
	private String title;
	private Integer procategoryId;
	private Date date;
	private Integer browses;
	private String contents;
	private String proFile;

	public Project() {
	}

	public Project(int projectId, String title) {
		this.projectId = projectId;
		this.title = title;
	}

	public Project(int projectId, String title, Integer procategoryId,
			Date date, Integer browses, String contents,
			String proFile) {
		this.projectId = projectId;
		this.title = title;
		this.procategoryId = procategoryId;
		this.date = date;
		this.browses = browses;
		this.contents = contents;
		this.proFile = proFile;
	}

	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getProcategoryId() {
		return this.procategoryId;
	}

	public void setProcategoryId(Integer procategoryId) {
		this.procategoryId = procategoryId;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getBrowses() {
		return this.browses;
	}

	public void setBrowses(Integer browses) {
		this.browses = browses;
	}

	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	public String getProFile() {
		return this.proFile;
	}

	public void setProFile(String proFile) {
		this.proFile = proFile;
	}

}
