package com.realty.base.model;

// Generated 2014-4-13 11:32:40 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * Region generated by hbm2java
 */
public class Region implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int regionId;
	private String regionName;

	public Region() {
	}

	public Region(int regionId) {
		this.regionId = regionId;
	}

	public Region(int regionId, String regionName) {
		this.regionId = regionId;
		this.regionName = regionName;
	}

	public int getRegionId() {
		return this.regionId;
	}

	public void setRegionId(int regionId) {
		this.regionId = regionId;
	}

	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

}
