package com.realty.base.model;

// Generated 2014-5-26 19:27:00 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Secondhouse generated by hbm2java
 */
public class Secondhouse implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int houseId;
	private String houseName;
	private Integer regionId;
	private String propertyAdress;
	private String propertyName;
	private Integer usageId;
	private Date exchangeTime;
	private Double buildingArea;
	private Integer structureId;
	private String present;
	private Double exchangePrice;
	private Double exchangeTotle;
	private Integer pricetypeId;
	private Integer taxtypeId;
	private Double taxTotle;
	private Double taxSeller;
	private Double taxBuyer;
	private Integer decorateId;
	private String buildingTime;
	private String floorTotle;
	private Integer floorSaid;
	private Integer floorActual;
	private String roomRate;
	private String houseType;
	private String orientation;
	private String otherfile;
	private String introduction;
	private Double longitude;
	private Double latitude;
	private String saleTime;
	private Integer entryId;
	private String entryName;
	private Date entryTime;
	private String auditName;
	private Date auditTime;
	private Integer status;
	private String remarks;
	private Set<SedecoratePhoto> sedecoratePhotos = new HashSet<SedecoratePhoto>(
			0);
	private Set<SetypePhoto> setypePhotos = new HashSet<SetypePhoto>(0);

	public Secondhouse() {
	}

	public Secondhouse(int houseId) {
		this.houseId = houseId;
	}

	public Secondhouse(int houseId, String houseName, Integer regionId,
			String propertyAdress, String propertyName,
			Integer usageId, Date exchangeTime, Double buildingArea,
			Integer structureId, String present, Double exchangePrice,
			Double exchangeTotle, Integer pricetypeId, Integer taxtypeId,
			Double taxTotle, Double taxSeller, Double taxBuyer,
			Integer decorateId, String buildingTime,
			String floorTotle, Integer floorSaid, Integer floorActual,
			String roomRate, String houseType,
			String orientation, String otherfile,
			String introduction, Double longitude, Double latitude,
			String saleTime, Integer entryId, String entryName,
			Date entryTime, String auditName, Date auditTime,
			Integer status, String remarks,
			Set<SedecoratePhoto> sedecoratePhotos, Set<SetypePhoto> setypePhotos) {
		this.houseId = houseId;
		this.houseName = houseName;
		this.regionId = regionId;
		this.propertyAdress = propertyAdress;
		this.propertyName = propertyName;
		this.usageId = usageId;
		this.exchangeTime = exchangeTime;
		this.buildingArea = buildingArea;
		this.structureId = structureId;
		this.present = present;
		this.exchangePrice = exchangePrice;
		this.exchangeTotle = exchangeTotle;
		this.pricetypeId = pricetypeId;
		this.taxtypeId = taxtypeId;
		this.taxTotle = taxTotle;
		this.taxSeller = taxSeller;
		this.taxBuyer = taxBuyer;
		this.decorateId = decorateId;
		this.buildingTime = buildingTime;
		this.floorTotle = floorTotle;
		this.floorSaid = floorSaid;
		this.floorActual = floorActual;
		this.roomRate = roomRate;
		this.houseType = houseType;
		this.orientation = orientation;
		this.otherfile = otherfile;
		this.introduction = introduction;
		this.longitude = longitude;
		this.latitude = latitude;
		this.saleTime = saleTime;
		this.entryId = entryId;
		this.entryName = entryName;
		this.entryTime = entryTime;
		this.auditName = auditName;
		this.auditTime = auditTime;
		this.status = status;
		this.remarks = remarks;
		this.sedecoratePhotos = sedecoratePhotos;
		this.setypePhotos = setypePhotos;
	}

	public int getHouseId() {
		return this.houseId;
	}

	public void setHouseId(int houseId) {
		this.houseId = houseId;
	}

	public String getHouseName() {
		return this.houseName;
	}

	public void setHouseName(String houseName) {
		this.houseName = houseName;
	}

	public Integer getRegionId() {
		return this.regionId;
	}

	public void setRegionId(Integer regionId) {
		this.regionId = regionId;
	}

	public String getPropertyAdress() {
		return this.propertyAdress;
	}

	public void setPropertyAdress(String propertyAdress) {
		this.propertyAdress = propertyAdress;
	}

	public String getPropertyName() {
		return this.propertyName;
	}

	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}

	public Integer getUsageId() {
		return this.usageId;
	}

	public void setUsageId(Integer usageId) {
		this.usageId = usageId;
	}

	public Date getExchangeTime() {
		return this.exchangeTime;
	}

	public void setExchangeTime(Date exchangeTime) {
		this.exchangeTime = exchangeTime;
	}

	public Double getBuildingArea() {
		return this.buildingArea;
	}

	public void setBuildingArea(Double buildingArea) {
		this.buildingArea = buildingArea;
	}

	public Integer getStructureId() {
		return this.structureId;
	}

	public void setStructureId(Integer structureId) {
		this.structureId = structureId;
	}

	public String getPresent() {
		return this.present;
	}

	public void setPresent(String present) {
		this.present = present;
	}

	public Double getExchangePrice() {
		return this.exchangePrice;
	}

	public void setExchangePrice(Double exchangePrice) {
		this.exchangePrice = exchangePrice;
	}

	public Double getExchangeTotle() {
		return this.exchangeTotle;
	}

	public void setExchangeTotle(Double exchangeTotle) {
		this.exchangeTotle = exchangeTotle;
	}

	public Integer getPricetypeId() {
		return this.pricetypeId;
	}

	public void setPricetypeId(Integer pricetypeId) {
		this.pricetypeId = pricetypeId;
	}

	public Integer getTaxtypeId() {
		return this.taxtypeId;
	}

	public void setTaxtypeId(Integer taxtypeId) {
		this.taxtypeId = taxtypeId;
	}

	public Double getTaxTotle() {
		return this.taxTotle;
	}

	public void setTaxTotle(Double taxTotle) {
		this.taxTotle = taxTotle;
	}

	public Double getTaxSeller() {
		return this.taxSeller;
	}

	public void setTaxSeller(Double taxSeller) {
		this.taxSeller = taxSeller;
	}

	public Double getTaxBuyer() {
		return this.taxBuyer;
	}

	public void setTaxBuyer(Double taxBuyer) {
		this.taxBuyer = taxBuyer;
	}

	public Integer getDecorateId() {
		return this.decorateId;
	}

	public void setDecorateId(Integer decorateId) {
		this.decorateId = decorateId;
	}

	public String getBuildingTime() {
		return this.buildingTime;
	}

	public void setBuildingTime(String buildingTime) {
		this.buildingTime = buildingTime;
	}

	public String getFloorTotle() {
		return this.floorTotle;
	}

	public void setFloorTotle(String floorTotle) {
		this.floorTotle = floorTotle;
	}

	public Integer getFloorSaid() {
		return this.floorSaid;
	}

	public void setFloorSaid(Integer floorSaid) {
		this.floorSaid = floorSaid;
	}

	public Integer getFloorActual() {
		return this.floorActual;
	}

	public void setFloorActual(Integer floorActual) {
		this.floorActual = floorActual;
	}

	public String getRoomRate() {
		return this.roomRate;
	}

	public void setRoomRate(String roomRate) {
		this.roomRate = roomRate;
	}

	public String getHouseType() {
		return this.houseType;
	}

	public void setHouseType(String houseType) {
		this.houseType = houseType;
	}

	public String getOrientation() {
		return this.orientation;
	}

	public void setOrientation(String orientation) {
		this.orientation = orientation;
	}

	public String getOtherfile() {
		return this.otherfile;
	}

	public void setOtherfile(String otherfile) {
		this.otherfile = otherfile;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public String getSaleTime() {
		return this.saleTime;
	}

	public void setSaleTime(String saleTime) {
		this.saleTime = saleTime;
	}

	public Integer getEntryId() {
		return this.entryId;
	}

	public void setEntryId(Integer entryId) {
		this.entryId = entryId;
	}

	public String getEntryName() {
		return this.entryName;
	}

	public void setEntryName(String entryName) {
		this.entryName = entryName;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

	public String getAuditName() {
		return this.auditName;
	}

	public void setAuditName(String auditName) {
		this.auditName = auditName;
	}

	public Date getAuditTime() {
		return this.auditTime;
	}

	public void setAuditTime(Date auditTime) {
		this.auditTime = auditTime;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Set<SedecoratePhoto> getSedecoratePhotos() {
		return this.sedecoratePhotos;
	}

	public void setSedecoratePhotos(Set<SedecoratePhoto> sedecoratePhotos) {
		this.sedecoratePhotos = sedecoratePhotos;
	}

	public Set<SetypePhoto> getSetypePhotos() {
		return this.setypePhotos;
	}

	public void setSetypePhotos(Set<SetypePhoto> setypePhotos) {
		this.setypePhotos = setypePhotos;
	}

}
