package com.realty.base.model;

// Generated 2014-5-26 19:27:00 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * SetypePhoto generated by hbm2java
 */
public class SetypePhoto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int typephotoId;
	private int houseId;
	private String photopath;

	public SetypePhoto() {
	}

	public SetypePhoto(int typephotoId) {
		this.typephotoId = typephotoId;
	}

	public SetypePhoto(int typephotoId, int houseId,
			String photopath) {
		this.typephotoId = typephotoId;
		this.houseId = houseId;
		this.photopath = photopath;
	}

	public int getTypephotoId() {
		return this.typephotoId;
	}

	public void setTypephotoId(int typephotoId) {
		this.typephotoId = typephotoId;
	}

	public int getHouseId() {
		return this.houseId;
	}

	public void setHouseId(int houseId) {
		this.houseId = houseId;
	}

	public String getPhotopath() {
		return this.photopath;
	}

	public void setPhotopath(String photopath) {
		this.photopath = photopath;
	}

}
