package com.realty.base.model;

// Generated 2014-5-27 21:22:47 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * TaxType generated by hbm2java
 */
public class TaxType implements java.io.Serializable {

	private int taxtypeId;
	private String taxtypeName;

	public TaxType() {
	}

	public TaxType(int taxtypeId) {
		this.taxtypeId = taxtypeId;
	}

	public TaxType(int taxtypeId, String taxtypeName) {
		this.taxtypeId = taxtypeId;
		this.taxtypeName = taxtypeName;
	}

	public int getTaxtypeId() {
		return this.taxtypeId;
	}

	public void setTaxtypeId(int taxtypeId) {
		this.taxtypeId = taxtypeId;
	}

	public String getTaxtypeName() {
		return this.taxtypeName;
	}

	public void setTaxtypeName(String taxtypeName) {
		this.taxtypeName = taxtypeName;
	}

}
