
				<div class="wrap">
					<!-- Header Start -->
					<header id="header">
						<!-- Header Top Bar Start -->
						<div class="top-bar">
							<div class="slidedown collapse">
								<div class="container">
									<div class="phone-email pull-left">
										<a>
											<i class="icon-phone"></i> Call Us : +880 12345678
										</a>
										<a href="mail%40example.html">
											<i class="icon-envelope"></i> Email : mail@example.com
										</a>
									</div>
									<div class="pull-right">
										<ul class="social pull-left">
											<div id="search-form" class="pull-right">
												<%
							if(membername!=null)
												{%>
												当前用户：<a href="/realty/website/login/changepwd.jsp">
													<%=membername%>
												</a>
												<a href="/realty/website/login/loginout.jsp">注销</a>
											</div></td><%}
						else{
											%>

											<a href="/realty/website/login/login.jsp">登录</a>
											<a href="/realty/website/login/register.jsp">注册</a>
											<%} %>
										</ul>

										<div id="search-form" class="pull-right">
											<form action="#" method="get">
												<input type="text" class="search-text-box">
                           </form>
										</div>
									</div>
								</div>
							</div>
						</div>

						<!-- Header Top Bar End -->
						<!-- Main Header Start -->
						<div class="main-header">
							<div class="container">
								<!-- TopNav Start -->
								<div class="topnav navbar-header">
									<a class="navbar-toggle down-button" data-toggle="collapse" data-target=".slidedown">
										<i class="icon-angle-down icon-current"></i>
									</a>
								</div>
								<!-- TopNav End -->
								<!-- Logo Start -->
								<div class="logo pull-left">
									<h1>
										<a href="index-2.html">
											<img src="/realty/images/website/logo.jpg" alt="pixma" width="90" height="60">
                        </a>
									</h1>
								</div>
								<!-- Logo End -->
								<!-- Mobile Menu Start -->
								<div class="mobile navbar-header">
									<a class="navbar-toggle" data-toggle="collapse" href=".html">
										<i class="icon-reorder icon-2x"></i>
									</a>
								</div>
								<!-- Mobile Menu End -->
								<!-- Menu Start -->
								<nav class="collapse navbar-collapse menu">
									<ul class="nav navbar-nav sf-menu">
										<li>
											<a id="current" href="/realty/website/home.jsp">
												主      页
												<span class="sf-sub-indicator">
													<i class="icon-angle-down "></i>
												</span>
											</a>
											<!-- <ul>
                              <li><a href="index-3.html" class="sf-with-ul">Home 2</a></li>
                              <li><a href="index-4.html" class="sf-with-ul">Home 3</a></li>
                              <li><a href="index-nivo.html" class="sf-with-ul">Nivo Slider</a></li>
                           </ul> -->
										</li>
										<li>
											<a href="/realty/website/fmtpages/businessline.jsp" class="sf-with-ul">
												业务范围
												<span class="sf-sub-indicator">
													<i class="icon-angle-down "></i>
												</span>
											</a>
											<ul>
<li>
													<a href="/realty/website/fmtpages/serviceguide.jsp?earth=db" class="sf-with-ul">业务指引</a>
												</li>												<li>
													<a href="/realty/website/fmtpages/businessline.jsp?earth=db" class="sf-with-ul">土地一级市场</a>
												</li>
												<li>
													<a href="/realty/website/fmtpages/businessline.jsp?earth=qy" class="sf-with-ul">土地二级市场</a>
												</li>
												<li>
													<a href="/realty/website/fmtpages/businessline.jsp?earth=pg" class="sf-with-ul">房地产评估</a>
												</li>
												<li>
													<a href="/realty/website/fmtpages/businessline.jsp?earth=ch" class="sf-with-ul">土地代理</a>
												</li>
												<li>
													<a href="/realty/website/fmtpages/businessline.jsp?earth=zz" class="sf-with-ul">可行性研究</a>
												</li>
												<li>
													<a href="/realty/website/fmtpages/businessline.jsp?earth=fc" class="sf-with-ul">房产测绘</a>
												</li>
												<!-- <li>
                                 <a href="#" class="sf-with-ul"> 
                                 Third Level Menu 
                                 <span class="sf-sub-indicator pull-right">
                                 <i class="icon-angle-right "></i>
                                 </span>
                                 </a>
                                 <ul>
                                    <li><a href="#" class="sf-with-ul">Menu Item</a></li>
                                    <li><a href="#" class="sf-with-ul">Menu Item</a></li>
                                    <li><a href="#" class="sf-with-ul">Menu Item</a></li>
                                 </ul>
                              </li>-->
											</ul>
										</li>
										<li>
											<a href="/realty/website/fmtpages/aboutus.jsp" class="sf-with-ul">
												页面指引
												<span class="sf-sub-indicator">
													<i class="icon-angle-down "></i>
												</span>
											</a>
											<ul>
												<li>
													<a href="/realty/website/fmtpages/aboutus.jsp" class="sf-with-ul">关于我们</a>
												</li>
												<li>
													<a href="/realty/website/fmtpages/eastadvantage.jsp" class="sf-with-ul">东部优势</a>
												</li>
												<li>
													<a href="/realty/website/fmtpages/partner.jsp" class="sf-with-ul">合作伙伴</a>
												</li>
<li>
													<a href="/realty/website/fmtpages/serviceguide.jsp" class="sf-with-ul">服务指南</a>
												</li>
												<li>
													<a href="/realty/website/dynpages/projects.jsp" class="sf-with-ul">重要项目</a>
												</li>
												
												<li>
													<a href="/realty/website/dynpages/news.jsp" class="sf-with-ul">新闻动态</a>
												</li>
												<li>
													<a href="/realty/website/dynpages/laws.jsp" class="sf-with-ul">政策法规</a>
												</li>
												<li>
													<a href="/realty/website/dynpages/research.jsp" class="sf-with-ul">研究发布</a>
												</li>
												<li>
													<a href="/realty/website/dynpages/cultures.jsp" class="sf-with-ul">企业文化</a>
												</li>


											</ul>
										</li>
										<li>
											<a href="/realty/website/building/serbuilding.jsp" class="sf-with-ul">
												查看
												<span class="sf-sub-indicator">
													<i class="icon-angle-down "></i>
												</span>
											</a>
											<ul>
												<li>
													<a href="/realty/website/building/serbuilding.jsp" class="sf-with-ul">新   房</a>
												</li>
												<li>
													<a href="/realty/website/secondbuilding/sersebuilding.jsp" class="sf-with-ul">二手房</a>
												</li>
												
												<li>
													<a href="/realty/website/land/serland.jsp" class="sf-with-ul">土  地</a>
												</li>
												
											</ul>
										</li>
										
										<li>
											<a href="/realty/website/fmtpages/contactus.jsp">联系我们</a>
										</li>
									</ul>
								</nav>
								<!-- Menu End -->
							</div>
						</div>
						<!-- Main Header End -->
					</header>
					<div class="marqueeSized1">
					</div>

<script src="/realty/js/website/jquery.min.js"></script>
      <script src="/realty/js/website/bootstrap.js"></script>
      <script src="/realty/js/website/jquery.parallax.js"></script> 
      <script src="/realty/js/website/revolution-slider/js/jquery.themepunch.revolution.min.js"></script>
      <script src="/realty/js/website/jquery.prettyPhoto.js"></script>
      <script src="/realty/js/website/jquery.sticky.js"></script>
      <script src="/realty/js/website/jflickrfeed.js"></script>
      <script src="/realty/js/website/imagesloaded.pkgd.min.js"></script>
      <script src="/realty/js/website/spectrum.js"></script>
      <script src="/realty/js/website/custom.js"></script>